### ISSUE TITLE
Improve workflow name validation for argo

### ISSUE THREAD

**Issue by irtzonevrakis** [kantale/OpenBio.eu#218]
OpenBio allows users to enter workflow names which are invalid in the argo environment, rendering the resulting argo yaml file unusable.

Steps to reproduce:

(1) Create a new workflow named eg. ABC1
(2) Export to argo yaml
(3) Try uploading to an argo instance. Output is:
` Bad Request: Workflow.argoproj.io "ABC1--1qmf6v" is invalid: [metadata.generateName: Invalid value: "ABC1--1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "ABC1--1qmf6v": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]: Reload `

Proposed solution: Validate name using provided regex before allowing workflow creation

**Comment by kantale** [comment]
I believe changing the validation process for all tool names is a very drastic change. Since argo executor (as all other executors) take as input a DAG we could simply traverse the DAG and change the tool names. Since all components (tools/steps/...) communicate through BASH variables this shouldn't generate any side effect. 

Proposed solution: change all tool names with a function that looks like this:
```python
def argo_tool_name(tool_name):
   return 'tool_' + tool_name.lower()
```

**Comment by kantale** [comment]
This brings forward another issue! tool_names are not validated at server side. Someone could deliberately manipulate local javascript to create invalid tool names and corrupt the database!

**Comment by irtzonevrakis** [comment]
Proposed PR: #219
